# NumPy

A complete beginner-friendly guide to mastering NumPy with practical examples.

---

## What is NumPy?

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.
NumPy is a powerful Python library used for:
- Numerical computing
- Working with arrays
- Mathematical operations

It is the foundation for data science and machine learning.

## Installation Instructions

It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:

conda install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

## Array Creation
NumPy provides multiple ways to create arrays depending on your needs.

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
list = [1,2,3]
arr = np.array(list)
arr

array([1, 2, 3])

In [4]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### zeros and ones

Generate arrays of zeros or ones

In [5]:
# Create an array filled with zeros (2 rows, 3 columns)
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Create an array filled with ones
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

### arange

Return evenly spaced values within a given interval.

In [7]:
# Create values from 0 to 10 (exclusive) with step 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### linspace
Return evenly spaced numbers over a specified interval.

In [8]:
# Create 5 evenly spaced numbers between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Random 


In [9]:
# Create a 2x2 array with random values between 0 and 1
np.random.rand(2, 2)

array([[0.3583121 , 0.8774376 ],
       [0.67206065, 0.60748122]])

## Array Attributes

These properties help you understand the structure of your array.

In [10]:
arr = np.array([[1, 2], [3, 4]])

# shape: dimensions of the array
# ndim: number of dimensions
# size: total number of elements
# dtype: data type of elements

arr.shape, arr.ndim, arr.size, arr.dtype

((2, 2), 2, 4, dtype('int32'))

## Operations
NumPy allows element-wise operations and matrix operations.

In [12]:
a = np.array([1, 2])
b = np.array([3, 4])

print(a + b)   # addition
print(a * b)    # multiplication

[4 6]
[3 8]


In [13]:
# Matrix multiplication (dot product)
# Each row of the first matrix is multiplied by each column of the second matrix
np.dot(
    np.array([[1, 2], [3, 4]]),
    np.array([[5, 6], [7, 8]])
)

array([[19, 22],
       [43, 50]])

In [15]:
# Basic statistics
arr = np.array([1, 2, 3])

total = np.sum(arr)  # total sum
print(total)
ave = np.mean(arr) # average
print(ave)
maximum = np.max(arr)  # maximum value
print(maximum)
minimum = np.min(arr)  # minimum value
print(minimum)

6
2.0
3
1


In [16]:
# Standard deviation (spread of values)
# Standard deviation measures how spread out values are from the mean
# Low std → values are close to the mean
# High std → values are more spread out
np.std(np.array([1, 2, 3, 4, 5]))

1.4142135623730951

## Indexing & Slicing

Access specific elements or parts of the array.

In [17]:
arr = np.array([10, 20, 30])

arr[0]  # Access first element

10

In [18]:
arr = np.array([10, 20, 30, 40])

arr[1:3]  # Slice elements from index 1 to 3 (exclusive)

array([20, 30])

In [19]:
arr = np.array([[1, 2], [3, 4]])

arr[0, 1]  # Access element in 2D array (row 0, column 1)

2

In [20]:
# Boolean indexing (filter values > 3)
arr = np.array([1, 5, 2, 8])

arr[arr > 3]

array([5, 8])

## Reshaping
Change the structure of arrays without changing the data.

In [32]:
arr = np.arange(6)
print("arr = {}".format(arr))

reshape = arr.reshape(2, 3)  # Reshape array into 2 rows and 3 columns
print("reshape = {}".format(reshape))


arr = [0 1 2 3 4 5]
reshape = [[0 1 2]
 [3 4 5]]


In [33]:
np.array([[1, 2], [3, 4]]).flatten()  # Flatten array into 1D

array([1, 2, 3, 4])

In [34]:
np.array([[1, 2], [3, 4]]).T  # Transpose rows and columns

array([[1, 3],
       [2, 4]])

## Practice Exercises

Try solving these:

1. Create a NumPy array from 0 to 20 with step 2  
2. Create a 3x3 matrix filled with ones  
3. Find the mean of [10, 20, 30, 40]  
4. Reshape an array of 12 elements into (3,4)  
5. Filter values greater than 5 from an array  

### Practice Tips

Try solving each exercise before running the solution.
Focus on understanding, not memorization.

# Great !